from os import PathLike
from typing import Any, Iterable

class RefkitError(Exception): ...
class MissingReferenceError(RefkitError): ...

class Entry:
    @property
    def key(self) -> str: ...
    @property
    def entry_type(self) -> str: ...
    @property
    def title(self) -> str | None: ...
    @property
    def parent(self) -> Entry | None: ...
    @property
    def parents(self) -> list[Entry]: ...
    @property
    def volume(self) -> str | None: ...
    @property
    def doi(self) -> str | None: ...

class Library:
    @staticmethod
    def read(path: str | PathLike[str], strict: bool = True, diagnostics: bool = False) -> Library: ...
    @staticmethod
    def parse(
        source: str,
        format: str = "bibtex",
        strict: bool = True,
        diagnostics: bool = False,
    ) -> Library: ...
    @property
    def diagnostics(self) -> list[str]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Entry]: ...
    def get(self, key: str) -> Entry | None: ...
    def is_empty(self) -> bool: ...
    def select(self, selector: str) -> list[Entry]: ...
    def to_dicts(self) -> Any: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> Entry: ...

class Style:
    @staticmethod
    def load(name: str) -> Style: ...
    @staticmethod
    def from_xml(xml: str) -> Style: ...
    @staticmethod
    def from_path(path: str | PathLike[str]) -> Style: ...
    @property
    def id(self) -> str: ...
    @property
    def title(self) -> str: ...

class Locale:
    @staticmethod
    def load(code: str) -> Locale: ...
    @property
    def code(self) -> str: ...

class Cite:
    def __init__(self, key: str, locator: str | None = None, label: str | None = None) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def locator(self) -> str | None: ...
    @property
    def label(self) -> str | None: ...

class Rendered:
    @property
    def text(self) -> str: ...
    @property
    def html(self) -> str: ...
    @property
    def tree(self) -> Any: ...
    def to_text(self) -> str: ...
    def to_html(self) -> str: ...
    def to_tree(self) -> Any: ...

class Document:
    def __init__(self, library: Library, style: Style, locale: str | Locale | None = None) -> None: ...
    def cite(self, items: str | Cite | Iterable[str | Cite]) -> Rendered: ...
    def bibliography(self, all: bool = False) -> Rendered: ...

class BibField:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...
    @property
    def span(self) -> tuple[int, int]: ...

class BibFieldMap:
    def keys(self) -> list[str]: ...
    def is_empty(self) -> bool: ...
    def get(self, key: str) -> BibField | None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> BibField: ...

class BibEntry:
    @property
    def key(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def fields(self) -> BibFieldMap: ...
    @property
    def span(self) -> tuple[int, int]: ...

class BibEntryMap:
    def keys(self) -> list[str]: ...
    def is_empty(self) -> bool: ...
    def get(self, key: str) -> BibEntry | None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> BibEntry: ...

class BibDocument:
    @staticmethod
    def read(path: str | PathLike[str]) -> BibDocument: ...
    @staticmethod
    def parse(source: str) -> BibDocument: ...
    @property
    def entries(self) -> BibEntryMap: ...
    @property
    def comments(self) -> list[str]: ...
    @property
    def preamble(self) -> str: ...
    @property
    def strings(self) -> dict[str, str]: ...
    @property
    def failed_blocks(self) -> list[dict[str, Any]]: ...
    @property
    def blocks(self) -> list[dict[str, Any]]: ...
    def write(self, path: str | PathLike[str] | None = None) -> None: ...
