lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "agent-plugins"
version = "0.1.1"

[[packages.wheels]]
name = "agent_plugins-0.1.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/d1/21/3ebab3b138cf09e262321b4faa17a6e94fb23148d5be755f393c8e3869ea/agent_plugins-0.1.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "30a4129ba7c8bdebb24fbf15a3ddbea346dc13c1ec5dcc69df0c9a48c091f67a"

[[packages]]
name = "iniconfig"
version = "2.3.0"

[[packages.wheels]]
name = "iniconfig-2.3.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/iniconfig-2.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "1cd8448eea1c863c970703ed01fa1baf655043150cee772772253e3461b701ed"

[[packages]]
name = "packaging"
version = "26.3"

[[packages.wheels]]
name = "packaging-26.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/63/34/ba1c580383c9eada3711951fef0795c80b829a078d72188184bcab9dd527/packaging-26.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "d7193f7c8e4e93f444fde0262bf90af30e16fa0ad0ad44cb553c87339b23cd1c"

[[packages]]
name = "pluggy"
version = "1.6.0"

[[packages.wheels]]
name = "pluggy-1.6.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/pluggy-1.6.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "8358dcb4259589a6dbb54b42d0c437801bac4c69e843e617e3b529e9b7926fda"

[[packages]]
name = "polars"
version = "1.33.1"

[[packages.wheels]]
name = "polars-1.33.1-cp314-cp314-pyemscripten_2026_0_wasm32.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/polars-1.33.1-cp314-cp314-pyemscripten_2026_0_wasm32.whl"

[packages.wheels.hashes]
sha256 = "3eefe347ffa293521fe54b25b4bd89baea72017eb0738c23dec9028643f66b1b"

[[packages]]
name = "pygments"
version = "2.21.0"

[[packages.wheels]]
name = "pygments-2.21.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/71/46/17f022dd3e953bf20a04a028a21ec746d942f8d2af30fa0f124fa0e6a684/pygments-2.21.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "2363c69b61c4a97c838da3b130dcd6468f4848992b21a82f2a63ec34377137d9"

[[packages]]
name = "pytest"
version = "9.1.1"

[[packages.wheels]]
name = "pytest-9.1.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/24/25/1de2678b631f5a49215c6c96fff41ba892b0a34df68d6d80292b1b48aa7f/pytest-9.1.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "37a86b45efb9a47a61a36449063e8e18d0cab3161329fc099eb21783169c4f0c"
