from collections.abc import Iterable
from os import PathLike
from typing import Literal, TypeAlias

from .types import (
    BibliographyLayout,
    Diagnostic,
    ProjectionRow,
    RawBlock,
    RawFailedBlock,
    RenderedTree,
    ResolvedBibEntry,
    TidyRename,
)

__version__: str
build_info: str
build_mode: Literal["debug", "release"]
_RecoveryPolicy: TypeAlias = Literal["error", "report"]
_DuplicateRule: TypeAlias = Literal["doi", "key", "abstract", "citation"]
_MergeStrategy: TypeAlias = Literal["first", "last", "combine", "overwrite"]

class RefkitError(Exception): ...

class ParseError(RefkitError):
    diagnostics: list[Diagnostic]

class MissingReferenceError(RefkitError): ...
class TidyError(RefkitError): ...

class TidySyntaxError(TidyError):
    line: int
    column: int
    byte: int
    character: str | None
    message: str

class TidyOptions:
    def __init__(
        self,
        *,
        omit: Iterable[str] | None = None,
        curly: bool = False,
        numeric: bool = False,
        months: bool = False,
        space: int = 2,
        tab: bool = False,
        align: bool | int | None = 14,
        blank_lines: bool = False,
        sort: bool | Iterable[str] | None = None,
        duplicates: Iterable[_DuplicateRule] | None = None,
        merge: _MergeStrategy | None = None,
        strip_enclosing_braces: bool = False,
        drop_all_caps: bool = False,
        escape: bool = True,
        sort_fields: bool | Iterable[str] | None = None,
        strip_comments: bool = False,
        trailing_commas: bool = False,
        encode_urls: bool = False,
        tidy_comments: bool = True,
        remove_empty_fields: bool = False,
        remove_duplicate_fields: bool = True,
        generate_keys: bool | str | None = None,
        max_authors: int | None = None,
        lowercase: bool = True,
        enclosing_braces: bool | Iterable[str] | None = None,
        remove_braces: bool | Iterable[str] | None = None,
        wrap: bool | int | None = None,
    ) -> None: ...

class TidyWarning:
    @property
    def code(self) -> Literal["missing_key", "duplicate_entry"]: ...
    @property
    def rule(self) -> _DuplicateRule | None: ...
    @property
    def message(self) -> str: ...

class TidyResult:
    @property
    def bibtex(self) -> str: ...
    @property
    def warnings(self) -> list[TidyWarning]: ...
    @property
    def renames(self) -> list[TidyRename]: ...
    @property
    def count(self) -> int: ...

def tidy_bibtex(source: str, *, options: TidyOptions | None = None) -> TidyResult: ...
def _write_bibtex(path: str | PathLike[str], source: str) -> None: ...

class Entry:
    @property
    def key(self) -> str: ...
    @property
    def entry_type(self) -> str: ...
    @property
    def title(self) -> str | None: ...
    @property
    def date(self) -> str | None: ...
    @property
    def parents(self) -> list[Entry]: ...
    @property
    def volume(self) -> str | None: ...
    @property
    def doi(self) -> str | None: ...

class Library:
    @staticmethod
    def read(path: str | PathLike[str], *, recovery: _RecoveryPolicy = "error") -> Library: ...
    @staticmethod
    def parse_bibtex(
        source: str,
        *,
        recovery: _RecoveryPolicy = "error",
    ) -> Library: ...
    @staticmethod
    def parse_yaml(source: str) -> Library: ...
    @property
    def diagnostics(self) -> list[Diagnostic]: ...
    def keys(self) -> list[str]: ...
    def get_many(self, keys: Iterable[str]) -> list[Entry]: ...
    def values(self) -> list[Entry]: ...
    def get(self, key: str) -> Entry | None: ...
    def is_empty(self) -> bool: ...
    def select(self, selector: str) -> list[Entry]: ...
    def project(
        self, fields: Iterable[str] | None = None, *, keys: Iterable[str] | None = None
    ) -> list[ProjectionRow]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> Entry: ...

class Style:
    @staticmethod
    def load(name: str) -> Style: ...
    @staticmethod
    def from_xml(xml: str) -> Style: ...
    @staticmethod
    def from_path(path: str | PathLike[str]) -> Style: ...
    @property
    def id(self) -> str: ...
    @property
    def title(self) -> str: ...

class Locale:
    @staticmethod
    def load(code: str) -> Locale: ...
    @property
    def code(self) -> str: ...

class Cite:
    def __init__(
        self, key: str, *, locator: str | None = None, label: str | None = None
    ) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def locator(self) -> str | None: ...
    @property
    def label(self) -> str | None: ...

class CitationGroup:
    def __init__(self, items: Iterable[str | Cite]) -> None: ...
    @property
    def items(self) -> list[Cite]: ...
    def __len__(self) -> int: ...

class Citation:
    def __init__(
        self, id: str, citation: str | Cite | CitationGroup, *, note_number: int | None = None
    ) -> None: ...
    @property
    def note_number(self) -> int | None: ...
    @property
    def id(self) -> str: ...
    @property
    def group(self) -> CitationGroup: ...

class Rendered:
    @property
    def layout(self) -> BibliographyLayout | None: ...
    @property
    def text(self) -> str: ...
    @property
    def html(self) -> str: ...
    @property
    def tree(self) -> RenderedTree: ...

class RenderedDocument:
    @property
    def citation_order(self) -> list[str]: ...
    @property
    def citations(self) -> dict[str, Rendered]: ...
    @property
    def bibliography(self) -> Rendered: ...
    def __getitem__(self, id: str) -> Rendered: ...

class Document:
    def __init__(
        self, library: Library, style: Style, *, locale: str | Locale | None = None
    ) -> None: ...
    def render(self, citations: Iterable[Citation]) -> RenderedDocument: ...
    def cited_bibliography(self, citations: Iterable[Citation]) -> Rendered: ...
    def full_bibliography(self) -> Rendered: ...

class BibField:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...
    @property
    def span(self) -> tuple[int, int]: ...

class BibFieldMap:
    def unique_keys(self) -> list[str]: ...
    def occurrence_keys(self) -> list[str]: ...
    def occurrences(self) -> list[BibField]: ...
    def get_all(self, key: str) -> list[BibField]: ...
    def is_empty(self) -> bool: ...
    def get_unique(self, key: str) -> BibField | None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> BibField: ...

class BibEntry:
    @property
    def key(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def fields(self) -> BibFieldMap: ...
    @property
    def span(self) -> tuple[int, int]: ...

class BibEntryMap:
    def unique_keys(self) -> list[str]: ...
    def occurrence_keys(self) -> list[str]: ...
    def occurrences(self) -> list[BibEntry]: ...
    def get_all(self, key: str) -> list[BibEntry]: ...
    def is_empty(self) -> bool: ...
    def get_unique(self, key: str) -> BibEntry | None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> BibEntry: ...

class BibDocument:
    @property
    def diagnostics(self) -> list[Diagnostic]: ...
    @staticmethod
    def read(path: str | PathLike[str]) -> BibDocument: ...
    @staticmethod
    def parse(source: str) -> BibDocument: ...
    @property
    def entries(self) -> BibEntryMap: ...
    @property
    def comments(self) -> list[str]: ...
    @property
    def preamble(self) -> str: ...
    @property
    def strings(self) -> dict[str, str]: ...
    @property
    def failed_blocks(self) -> list[RawFailedBlock]: ...
    @property
    def blocks(self) -> list[RawBlock]: ...
    def to_bibtex(self) -> str: ...
    def resolve(self) -> list[ResolvedBibEntry]: ...
    def tidy(self, *, options: TidyOptions | None = None) -> TidyResult: ...
    def write(self, path: str | PathLike[str]) -> None: ...
